branch-defaults:
  master:
    environment: psiRbase-env
    group_suffix: null
environment-defaults:
  psiRbase-env:
    branch: null
    repository: null
  siRBase:
    branch: null
    repository: null
  srufbase-dev:
    branch: null
    repository: null
global:
  application_name: psiRbase
  branch: null
  default_ec2_keyname: theKeyPair
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
