# Generated by Django 2.0.2 on 2018-03-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CelegansBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrNum', models.CharField(default='N/A', max_length=50)),
                ('startPos', models.CharField(default='N/A', max_length=20)),
                ('endPos', models.CharField(default='N/A', max_length=20)),
                ('sirName', models.CharField(default='N/A', max_length=50)),
                ('sign', models.CharField(default='?', max_length=1)),
                ('author', models.CharField(default='N/A', max_length=100)),
                ('stage', models.CharField(default='N/A', max_length=100)),
                ('pubmed_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CelegansSirna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
