# Generated by Django 2.0.2 on 2018-02-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CelegansSirna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=50)),
                ('stage', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CelegansSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('pubmed_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SusDomesticusSirna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('stage', models.CharField(default='N/A', max_length=100)),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.CelegansSource')),
            ],
        ),
        migrations.CreateModel(
            name='SusDomesticusSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('pubmed_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='celeganssirna',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.CelegansSource'),
        ),
    ]
