# Generated by Django 2.0.2 on 2018-02-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celeganssirna',
            name='source',
        ),
        migrations.DeleteModel(
            name='CelegansSirna',
        ),
    ]
