# Generated by Django 2.0.2 on 2018-03-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celegansbed',
            old_name='chrNum',
            new_name='chr_num',
        ),
        migrations.RenameField(
            model_name='celegansbed',
            old_name='sirName',
            new_name='sirname',
        ),
    ]
