# Generated by Django 2.0.2 on 2018-03-16 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180302_0426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CelegansBed',
        ),
    ]
