# Generated by Django 2.0.2 on 2018-02-21 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180221_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelegansSirna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=50)),
                ('stage', models.CharField(default='N/A', max_length=100)),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.CelegansSource')),
            ],
        ),
    ]
