# Generated by Django 2.0.2 on 2018-03-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_delete_celegansbed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelegansBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr_num', models.CharField(default='N/A', max_length=10)),
                ('start', models.CharField(default='N/A', max_length=20)),
                ('end', models.CharField(default='N/A', max_length=20)),
                ('name', models.CharField(default='N/A', max_length=30)),
                ('strand', models.CharField(default='?', max_length=1)),
                ('stage', models.CharField(default='N/A', max_length=50)),
                ('source', models.CharField(default='N/A', max_length=50)),
                ('pubmed_id', models.CharField(blank=True, max_length=12, null=True)),
                ('target_mrna', models.CharField(default='N/A', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='celeganssirna',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='celeganssirna',
            name='sequence',
            field=models.CharField(max_length=50),
        ),
    ]
