# Generated by Django 2.0.2 on 2018-03-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20180315_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelegansMrna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr_num', models.CharField(default='N/A', max_length=10)),
                ('start', models.CharField(default='N/A', max_length=20)),
                ('end', models.CharField(default='N/A', max_length=20)),
                ('name', models.CharField(default='N/A', max_length=30)),
                ('strand', models.CharField(default='?', max_length=1)),
            ],
        ),
    ]
