# Generated by Django 2.0.2 on 2018-03-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_celeganschrslicei'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelegansChrSliceII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('sequence', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CelegansChrSliceIII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('sequence', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CelegansChrSliceIV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('sequence', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CelegansChrSliceMtDNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('sequence', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CelegansChrSliceV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('sequence', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CelegansChrSliceX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('sequence', models.CharField(default='N/A', max_length=100)),
            ],
        ),
    ]
